name: Deploy to Staging

on:
  push:
    branches:
      - development

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      indexer: ${{ steps.filter.outputs.indexer }}
      server: ${{ steps.filter.outputs.server }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          filters: |
            indexer:
                - 'src/indexer/**/*'
            server:
                - 'src/api-server/**/*'

  indexer:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.indexer == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "setting variables"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/simple-search-indexer
          tags: ${{ steps.vars.outputs.sha_short }}
          workdir: src/indexer/

      - name: Set New Image
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.K8_SECRET_DEV }}
          KUBECTL_VERSION: "1.15"
        with:
          args: '"set image deployment/deployment-tattle-simplesearch-indexer container-tattle-simplesearch-indexer=tattletech/simple-search-indexer:${{steps.vars.outputs.sha_short}}"'

      - name: Verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.K8_SECRET_DEV }}
          KUBECTL_VERSION: "1.15"
        with:
          args: '"rollout status deployment/deployment-tattle-simplesearch-indexer"'

  server:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.server == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "setting variables"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/simple-search-server
          tags: ${{ steps.vars.outputs.sha_short }}
          workdir: src/api-server/
      - name: Set New Image
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.K8_SECRET_DEV }}
          KUBECTL_VERSION: "1.15"
        with:
          args: '"set image deployment/deployment-tattle-simplesearch-rest container-tattle-simplesearch-rest=tattletech/simple-search-server:${{steps.vars.outputs.sha_short}}"'
      - name: Verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.K8_SECRET_DEV }}
          KUBECTL_VERSION: "1.15"
        with:
          args: '"rollout status deployment/deployment-tattle-simplesearch-rest"'

  notify:
    runs-on: ubuntu-latest
    needs: [indexer, server]
    if: ${{ always() }}
    steps:
      - name: Notify on Slack
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Deployed Simple Server to Staging"
          SLACK_TITLE: "staging-deploy workflow complete"
          SLACK_COLOR: "#020637"
          SLACK_ICON: https://tattle-media.s3.amazonaws.com/monogram-dark.svg
